on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Protoc A
        uses: ./ # Uses an action in the root directory
        with:
          path: --proto_path=../ --go_out=../ --go_opt=paths=source_relative ../protoc-go-actions/testProto/A/A.proto
          parent: protoc-go-actions
      - name: Test Protoc B
        uses: ./ # Uses an action in the root directory
        with:
          path: --proto_path=../ --go_out=../ --go_opt=paths=source_relative ../protoc-go-actions/testProto/B/B.proto
          parent: protoc-go-actions
      - name: Check Result
        run: |
          ls ./testProto/A
          cat ./testProto/A/A.pb.go
