on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Protoc
        uses: ./ # Uses an action in the root directory
        with:
          path: --proto_path=../proto/testProto --go_out=./testProto --go_opt=paths=source_relative ../proto/testProto/A/A.proto
          # parent: proto
      - name: Check Result
        run: |
          ls ./testProto/A
          cat ./testProto/A/A.pb.go
