on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Proto
        uses: ./ # Uses an action in the root directory
        with:
					path: --proto_path=. --go_out=. --go_opt=paths=source_relative ./A/A.proto
					parentDir: CyclopsProto
			- name: Check Result
        run: ls
